#   This file contains all constants

#tracker list
trackerList = ["152.7.99.154","152.46.18.231"]#,"1.1.1.2","1.1.1.3"]
trackerPort = 9990

#client port
clientPort = 7070

#FLAG VALUES
REQ_FLAG =0
RES_FLAG = 128
NCONFLICT_FLAG = 64
USERNEXIST_FLAG = 32
EXIT_FLAG = 16
SERVER_FULL = 8

#CLIENT MESSAGE TYPES
CLIENT_PING_REQ_TYPE = 0
CLIENT_PING_RES_TYPE = 1
CLIENT_SEND_TYPE = 2
CLIENT_RECV_TYPE = 3

#CLIENT MESSAGE VALUES
CLIENT_PING_REQ_MSG = "HELLO"
CLIENT_PING_RES_OK_MSG = "OK"
CLIENT_PING_RES_WRNG_MSG = "WRNGID"

#ACTION VALUES
REGISTER = 0
QUERY = 1
EXIT = 2
SENDMESSAGE = 4
REPLYSTATUS = 8